### PR TITLE
Build Script & PML Info File

### PR DESCRIPTION
**Pull request by tajmone**
This commit adds:

- The `pml-version.txt` file to the repository root, with the required PML version.
- The `build.sh` script to convert the PML Ref Man after checking that:
    1. PML is installed on the user machine and
    2. that it matches the required version stored in the `pml-version.txt` file

    aborting with error if any of these conditions are not met.

Since _PML Ref Man_ in the `main` branch of this project always matches the latest PML version, I assumed that it would be a good precaution to add a build script that is capable of checking that the correct PML version is installed on the machine.

The script is also useful in case the user has forgot to update (i.e. `git pull`) the latest head from the upstream repository, if `pml-version.txt` was updated to a newer PML version.

Of course, the addition of `pml-version.txt` introduces the burden of having to update its contents whenever a new PML version is released — but I'm sure that can easily by automated via some CI script.

I haven't updated the REAMDE file yet, I wanted to first know what you think of this commit. If you want we can delaying merging the PR until I also update `README.md` accordingly, amend the commit and force push the PR again.

### CODE REVIEW

**Comment by pml-lang** [comment]
I have two suggestions:

- rename `pml-version.txt` to `VERSION`.
  Reason: I've seen other repositories using an uppercase name without extension, so it seems that it's considered good practice. I also intend to rename `version.txt` to `VERSION` in repo [converter](https://github.com/pml-lang/converter), and add a `VERSION` file to repo [user_manual](https://github.com/pml-lang/user-manual)

- Just create a warning in the build script (instead of aborting with an error) if the pmlc version on the user's machine is different.
  Reason: If the versions are different, there is still a good chance that the HTML files can be created. It will only fail if there are backwards incompatibilities with the PML syntax. Thus, the user is warned, but can still continue if he/she doesn't want to upgrade pmlc.

Sorry for my late reply. Yesterday was a holiday in Luxembourg, and I was quite busy before the long weekend.

**Comment by tajmone** [comment]
OK, I agree with your suggestions and I'll implement them, hopefully later on today — this morning I'll be busy taking the dog to the vet, so I'll have to procrastinate it.

 > Sorry for my late reply. Yesterday was a holiday in Luxembourg, and I was quite busy before the long weekend.
 
 Don't worry, it wasn't urgent. I'm also struggling with time lately, and have been caught up in some technical side issues on my PC that demanded my attention (breaking updates that forced me to read lots of docs to fix problems, etc.).

**Comment by tajmone** [comment]
# Done!

I've amended the commit as you suggested.

**Comment by pml-lang** [comment]
Thank you.

**Pull request merged**
